#ifndef UCSEVENT_H
#define UCSEVENT_H
namespace UCSEVENT
{
const char LOGINWIDGET[]="LOGINWIDGET";
const char MAINMENUWIDGET[]="MAINMENUWIDGET";
const char PREFACEWIDGET[]="PREFACEWIDGET";
const char ROSPOINTCLOUDRECIEVED[]="ROSPOINTCLOUDRECIEVED";


const char START_SYSTEM[]="START_SYSTEM";
const char EXIT_SYSTEM[]="EXIT_SYSTEM";
const char BUTTONHIT[]="BUTTONHIT";

const char LOGIN_USER[]="LOGIN_USER";

const char GOBACK[]="GOBACK";

const char CAR_INFO[]="CAR_INFO";
const char RETURNMAIN[]="RETURNMAIN";
const char STARTROSLOOP[]="STARTROSLOOP";
const char MQTTNETSET[]="MQTTNETSET";
const char NETWIDGET[]="NETWIDGET";
const char RETURNLOGINWIDGET[]="RETURNLOGINWIDGET";
const char NODELAUNCH[]="NODELAUNCH";
const char DEVICEMANAGE[]="DEVICEMANAGE";
const char ROSPUBCONTROLSIG[]="ROSPUBCONTROLSIG";


const char MQTTSTART[]="MQTTSTART";
const char MQTTSTOP[]="MQTTSTOP";


const char VEHICLE_1_REMOTE_CONTROL[]="VEHICLE_1_REMOTE_CONTROL";
const char CONTROLLER_CMD[]="CONTROLLER_CMD";
const char V1_AUTO[]="V1_AUTO";

const char V2_AUTO[]="V2_AUTO";

}
#endif
